### ISSUE TITLE
go-client: run `go fmt` after code generation.

### ISSUE THREAD

**Issue by matthewhartstonge** [FusionAuth/fusionauth-client-builder#28]
Hey team,

As a nice to have, it would be great to conform to standard Go code formatting by running [`go fmt`](https://blog.golang.org/gofmt) on both files after generation 😄

Makes it more uniform when reading/reviewing Go code 👍

For example:
![image](https://user-images.githubusercontent.com/6119549/111924021-24997200-8b07-11eb-8a40-37ef981edb80.png)

Becomes:
![image](https://user-images.githubusercontent.com/6119549/111924025-2bc08000-8b07-11eb-8904-69dcbacf9cd7.png)

(I would imagine this to be a similar thing with dart and [`dart format`](https://dart.dev/tools/dart-format))

**Comment by robotdan** [comment]
Thanks @matthewhartstonge  - was thinking we were doing that.. if not we'll add it.

https://github.com/FusionAuth/go-client/commit/bea924bc7470e1bf5084613d463660aea975d8b3
