### ISSUE TITLE
Repository Stutter

### ISSUE THREAD

**Issue by GrimTheReaper** [FusionAuth/fusionauth-client-builder#6]
I've noticed that all of the client library repositories start with fusionauth. In languages like go, this leads to package stuttering (`fusionauth/fusionauth-go-client`). Any reason why it shouldn't just be `{language}-client`?

**Comment by robotdan** [comment]
@GrimTheReaper this is just our pattern thus far. 

@matthew-altman Any potential issues you see with a change such as this?

**Comment by matthew-altman** [comment]
@robotdan It's a matter of renaming every client repo. Not hard, but there would be a lot of downstream repo changes as well...maven, npm, etc

**Comment by robotdan** [comment]
@matthew-altman what about just for Go, is the package stuttering an issue with Go?

**Comment by matthew-altman** [comment]
@robotdan No problem changing it for Go. It's not an issue, per se, but isn't idiomatic. I'll see what I can do.

**Comment by matthew-altman** [comment]
This has been resolved. Github automatically creates redirects for renamed repos, so existing usages should still be fine.
The README in the `go-client` repo has an updated example that shows it cleaned up as well.

**Comment by robotdan** [comment]
@matthew-altman just in case...  make sure you also update the Go doc page.
https://fusionauth.io/docs/v1/tech/client-libraries/go

**Comment by GrimTheReaper** [comment]
Neat. The only other weird oddity for the Go package is that everything is under `pkg`. Usually, if a repo is _just_ a library and not an application, the resources are under root. A good(ish) example can be found [here](https://github.com/gorilla/mux), although I wouldn't say that it is important enough to break.

**Comment by robotdan** [comment]
Thanks @GrimTheReaper the help is appreciated! 

@matthew-altman can you take a look at these issues, perhaps open another issue to track.
