### ISSUE TITLE
src/main/domain/io.fusionauth.domain.User.json missing username field

### ISSUE THREAD

**Issue by andrius4669** [FusionAuth/fusionauth-client-builder#70]
I'm using https://github.com/FusionAuth/go-client and it seems that newest versions no longer have Username field in User struct (current code uses something from 2020).
Upon some digging I've landed here & found out that it was removed in https://github.com/FusionAuth/fusionauth-client-builder/commit/c9a82b0f98285526617492cdc539b071cdb873aa#diff-944105f2fe047707376c0d76f2d9c69625e6c7f65f21fb6d0ba159e889282077
Could this field be restored?
It's still listed in https://fusionauth.io/docs/v1/tech/apis/users#create-a-user & https://fusionauth.io/docs/v1/tech/apis/registrations#create-a-user-and-registration-combined

**Comment by mooreds** [comment]
Hmmm. Looks like the `User` struct pulls in the `SecureIdentity` struct, which does have username:

https://github.com/FusionAuth/go-client/blob/master/pkg/fusionauth/Domain.go#L5016 

Do you have an example of a golang client call which sets username and doesn't work?

**Comment by andrius4669** [comment]
I actually overlooked it in SecureIdentity struct :facepalm: 
Old code directly initialized fusionauth.User struct and Username field was in there so it was complaining about missing field after update.
Sorry about the noise.

**Comment by mooreds** [comment]
@andrius4669 no worries, glad you figured it out!
